### PR TITLE
width made parametric

### PR DESCRIPTION
**Pull request by davutg**
Width parameter added to options. 250px default width changed to 300px.
250px is a bit narrow for iconic ones.

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Thank you for taking the time to create PR. But I am sorry, I don't think we need this. Thanks though.

**Comment by davutg** [comment]
I thank you for this useful plugin.
Maybe instead setting **max-width**  parametric would be more helpful. As you see from the images below dynamically setting it to 350px generated a better view for me.
image

BTW, calling **update** function and changing **hideAfter** param didn't work for me.

**Comment by kamranahmedse** [comment]
For the width, I don't think we need to do that with jquery, just add the CSS to overwride the width?!

For the **hideAfter**, thanks for letting me know. There is a PR for that, I am not getting enought time to review that, will merge it soon.

**Comment by davutg** [comment]
In css from my understanding there is a container and its class is jq-toast-wrap. 
IMO, For some toasts 300px is ideal , but for some toasts which we expect something like just a word , such as "Success!" it could be 200px. 

Which place do you think to override it is the best in such cases?

**Comment by kamranahmedse** [comment]
Maybe this:
```css
.jq-toast-wrap {
    max-width: 300px
}
```

**Comment by davutg** [comment]
Yes, this was my underlying idea. According to my need I've some long text and short text notifications.So, 300px can't be fixed to me. 

If we had an angular directive such as <Toast> we would consider creating some css, such as <Toast class="toast-wide toast-xlarge etc."></Toast>. For js implementation providing a parameter to adjust width is considerable. This could be a semantic expression, wide, large,xlarge,jubo etc. or a spesific number. Removing fixed width and defining max-width param could be a better fit for many cases. 
I agree this is not a big case talk on it much but considerable .

**Pull request closed without merging**
